# ML-10 — Content Action Playbook

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

The ranked queue is a decision-support list for human review. Items are ordered by the baseline action score, with the reason code explaining why an item received its recommended action.

### Reason codes and actions

| Reason code | Action | Why it is ranked |
|---|---|---|
| STALE_REFRESH | Refresh Content | The content has been inactive for a long period, so a human should check whether its information, structure, or search intent needs updating. |
| QUICK_WIN | Optimise Existing Content | The content shows an existing performance opportunity that may be addressable without a full rewrite. |

### Archetype → action mapping

- **Stale content → STALE_REFRESH → Refresh Content**
- **Existing content with a potential quick opportunity → QUICK_WIN → Optimise Existing Content**
- **Ambiguous or weak signals → Human review before assigning an action**

The score is a prioritisation signal, not a probability of success or a guaranteed estimate of business value.

The reason code explains the signal behind the recommendation. It does not prove that the recommended action will improve performance.

In [3]:
from pathlib import Path
import pandas as pd

queue_path = Path("../outputs/baseline_action_score.csv")

queue = pd.read_csv(queue_path)

print("Ranked queue loaded successfully.")
print("Rows:", len(queue))
print("Columns:", list(queue.columns))

display(queue.head(20))

Ranked queue loaded successfully.
Rows: 30000
Columns: ['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct', 'score', 'reason_code', 'action_label']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct,score,reason_code,action_label
0,content_bbca724138f2,client_6208ef0f77,1600.0,0.43,MEDIUM,3.76,keyword article,transactional,5614.0,37325.0,...,0.00,0.00,0.0,low,striking,down,-100.0,100.0,STALE_REFRESH,Refresh Content
1,content_40e140ba2934,client_8722616204,720.0,0.29,LOW,0.78,keyword article,transactional,3306.0,21228.0,...,6.25,5.56,0.0,low,page_1,flat,NaN,80.0,STALE_REFRESH,Refresh Content
2,content_02b0d6e30129,client_19581e27de,110.0,0.40,MEDIUM,0.59,keyword article,transactional,NaN,NaN,...,0.00,0.00,0.0,low,page_1,down,-95.6,80.0,STALE_REFRESH,Refresh Content
3,content_24abafed9707,client_8722616204,480.0,0.00,LOW,0.00,keyword article,transactional,3246.0,21393.0,...,0.00,50.00,0.0,low,top_3,down,-100.0,80.0,STALE_REFRESH,Refresh Content
4,content_3a93f78aa0a5,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,4629.0,32698.0,...,0.00,0.00,0.0,low,striking,down,-61.4,70.0,STALE_REFRESH,Refresh Content
5,content_1dcf67c62f50,client_d4735e3a26,NaN,NaN,NaN,NaN,keyword article,NaN,970.0,6985.0,...,0.00,100.00,0.0,low,page_1,down,-33.3,70.0,STALE_REFRESH,Refresh Content
6,content_928af3e22c80,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3118.0,20396.0,...,0.00,0.00,0.0,moderate,striking,down,-45.7,70.0,STALE_REFRESH,Refresh Content
7,content_ab27c30d81f4,client_4ec9599fc2,NaN,NaN,NaN,NaN,keyword article,NaN,1094.0,7718.0,...,0.00,30.00,0.0,low,page_1,stable,14.6,70.0,STALE_REFRESH,Refresh Content
8,content_b81e0f46cea9,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,3962.0,28232.0,...,0.00,0.00,0.0,low,striking,down,-80.8,70.0,STALE_REFRESH,Refresh Content
9,content_da54cb4484f1,client_d4735e3a26,NaN,NaN,NaN,NaN,keyword article,NaN,894.0,6946.0,...,0.00,100.00,0.0,low,page_1,flat,NaN,70.0,STALE_REFRESH,Refresh Content
10,content_f2b4acf220d9,client_19581e27de,10.0,0.83,HIGH,1.19,keyword article,transactional,NaN,NaN,...,0.00,0.00,0.0,low,striking,up,66.7,70.0,STALE_REFRESH,Refresh Content
11,content_56d7248c0b43,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,4658.0,33287.0,...,0.00,100.00,0.0,low,striking,stable,0.0,70.0,STALE_REFRESH,Refresh Content
12,content_a34d943a132c,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,4447.0,31154.0,...,0.00,33.33,0.0,low,striking,down,-52.4,70.0,STALE_REFRESH,Refresh Content
13,content_22ba8c872ab2,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,4277.0,29808.0,...,0.00,100.00,0.0,low,page_1,stable,12.5,70.0,STALE_REFRESH,Refresh Content
14,content_fe16a55cd13d,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3388.0,21742.0,...,2.38,38.64,0.0,good,striking,down,-52.2,70.0,STALE_REFRESH,Refresh Content
15,content_0af51f20a3da,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,4530.0,32105.0,...,0.00,60.00,0.0,low,page_1,down,-66.7,70.0,STALE_REFRESH,Refresh Content
16,content_11da248ff221,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,3915.0,27656.0,...,0.00,100.00,0.0,low,striking,stable,-13.0,70.0,STALE_REFRESH,Refresh Content
17,content_0a91db491d14,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3478.0,21948.0,...,5.13,41.76,0.0,good,striking,down,-51.8,70.0,STALE_REFRESH,Refresh Content
18,content_2e2a634851a0,client_d029fa3a95,0.0,0.00,LOW,0.00,keyword article,informational,3928.0,27740.0,...,0.00,50.00,0.0,low,striking,down,-28.1,70.0,STALE_REFRESH,Refresh Content
19,content_cf56e2e2e282,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,5125.0,33705.0,...,0.84,24.11,0.0,excellent,striking,down,-85.6,70.0,STALE_REFRESH,Refresh Content

### Ranked action queue

The ranked queue prioritizes content using the baseline action score. Higher-scoring items are reviewed first.

The main observed action in the top 20 is **Refresh Content**, with the reason code **STALE_REFRESH**. A smaller number of items are classified as **Optimise Existing Content** with **QUICK_WIN**.

The reason codes provide a simple explanation for why an item appears in the queue. They are intended as decision-support signals rather than automatic instructions.

The queue should be reviewed by a human before any content change is made, especially when search demand is low or missing, trend data is missing, or the observed decline may have another explanation.

## 2. Intended use and limits

This playbook is intended to help a content team prioritize which pages to review first and what type of action may be worth considering.

The scores and reason codes are decision-support signals. They do not prove that refreshing or optimising a page will improve performance.

The recommendations are most useful when the underlying search, ranking, traffic, and content signals are available and reasonably current.

The output should not be treated as an automatic publishing or deletion system. A human should review the content and its context before taking action.

In [5]:
# Basic summary of the decision-support queue

print("Number of content items:", len(queue))

print("\nAction distribution:")
display(
    queue["action_label"]
    .value_counts()
    .rename_axis("action")
    .reset_index(name="count")
)

print("\nReason-code distribution:")
display(
    queue["reason_code"]
    .value_counts()
    .rename_axis("reason_code")
    .reset_index(name="count")
)

print("\nScore summary:")
print(queue["score"].describe())

Number of content items: 30000

Action distribution:

                      action  count
0                    Monitor  17677
1       Improve Title & Meta  11118
2  Optimise Existing Content   1156
3            Refresh Content     49

Reason-code distribution:

     reason_code  count
0   LOW_PRIORITY  17677
1        CTR_FIX  11118
2      QUICK_WIN   1156
3  STALE_REFRESH     49

Score summary:
count    30000.000000
mean        19.936667
std         13.590517
min          0.000000
25%         10.000000
50%         10.000000
75%         30.000000
max        100.000000
Name: score, dtype: float64

## 3. Human review + the no-go list

### Human review rules

Before taking action on a recommendation, a human reviewer should:

1. Check that the content is still relevant to the target search intent.
2. Review the current search demand and ranking signals.
3. Check whether the observed decline could be seasonal or temporary.
4. Check for missing or unreliable input data.
5. Confirm that the recommended action makes sense for the content type.
6. Review the actual page before making any content changes.

The score and reason code should be treated as decision-support signals, not as automatic decisions.

### What should NOT be automated

The system should not automatically:

- Publish content changes.
- Delete or unpublish content.
- Change a page's search intent.
- Rewrite an entire article without human review.
- Make decisions based only on a single score.
- Treat missing data as evidence that content is performing poorly.
- Assume that every traffic decline means the content needs a refresh.

A human should remain responsible for the final action.

In [6]:
# Human-review rules and no-go cases

review_rules = {
    "priority": "Review higher-scoring items first.",
    "reason_check": "Confirm that the reason code matches the current content situation.",
    "data_check": "Check for missing, unusual, or stale inputs.",
    "content_check": "Review the actual page before taking action.",
    "external_factors": "Check for seasonality, campaigns, or other external changes.",
    "final_decision": "A human reviewer makes the final decision."
}

no_go_cases = [
    "Automatic publishing or editing",
    "Automatic deletion of content",
    "Automatically changing search intent",
    "Claiming guaranteed business impact",
    "Overriding human reviewers",
    "Acting when important inputs are missing or stale"
]

print("Human review rules:")
for key, value in review_rules.items():
    print(f"- {key}: {value}")

print("\nNo-go cases:")
for item in no_go_cases:
    print(f"- {item}")

Human review rules:
- priority: Review higher-scoring items first.
- reason_check: Confirm that the reason code matches the current content situation.
- data_check: Check for missing, unusual, or stale inputs.
- content_check: Review the actual page before taking action.
- external_factors: Check for seasonality, campaigns, or other external changes.
- final_decision: A human reviewer makes the final decision.

No-go cases:
- Automatic publishing or editing
- Automatic deletion of content
- Automatically changing search intent
- Claiming guaranteed business impact
- Overriding human reviewers
- Acting when important inputs are missing or stale

## 4. Monitoring / retrain triggers

The recommendations should be monitored because search behavior, rankings, and content performance can change over time.

Useful monitoring signals include:

- A noticeable change in the distribution of action labels or reason codes.
- A change in the score distribution compared with the data used to build the baseline.
- Increasing amounts of missing input data.
- A measured drop in model performance on newly available labelled data.
- Changes in search demand or ranking patterns that make the original rules less representative.

A retraining or review should be considered when these changes are persistent rather than caused by a short-term fluctuation.

The model should also be reviewed if human reviewers repeatedly disagree with the recommended actions. This can indicate that the features or decision rules are no longer aligned with practical content decisions.

These are monitoring and decision-support triggers, not automatic retraining rules.

In [7]:
# Simple monitoring summary for the current queue

print("Current queue size:", len(queue))

print("\nScore distribution:")
print(queue["score"].describe())

print("\nReason-code distribution:")
display(
    queue["reason_code"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .rename("percentage")
    .to_frame()
)

print("\nMissing values in important monitoring fields:")
monitor_cols = [
    "score",
    "reason_code",
    "action_label"
]

available_monitor_cols = [
    col for col in monitor_cols if col in queue.columns
]

display(queue[available_monitor_cols].isna().sum())

Current queue size: 30000

Score distribution:
count    30000.000000
mean        19.936667
std         13.590517
min          0.000000
25%         10.000000
50%         10.000000
75%         30.000000
max        100.000000
Name: score, dtype: float64

Reason-code distribution:

               percentage
reason_code
LOW_PRIORITY        58.92
CTR_FIX             37.06
QUICK_WIN            3.85
STALE_REFRESH        0.16

Missing values in important monitoring fields:

score           0
reason_code     0
action_label    0
dtype: int64

## 5. Exports for the paper

The ranked queue is exported to `work/outputs/` so that the paper can reuse the same decision-support output.

The exported queue contains the content identifier, action, reason code, and score needed to reproduce the prioritisation view.

The queue is an output for analysis and human review. It is not a production automation file.

In [8]:
from pathlib import Path

# Create the output directory if it does not already exist
output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

# Select the fields needed for the ranked decision-support queue
export_cols = [
    "content_id",
    "score",
    "reason_code",
    "action_label"
]

export_cols = [col for col in export_cols if col in queue.columns]

ranked_queue = queue[export_cols].copy()

# Rank from highest to lowest score
ranked_queue = ranked_queue.sort_values(
    "score",
    ascending=False
).reset_index(drop=True)

# Export queue
output_path = output_dir / "action_playbook_queue.csv"

ranked_queue.to_csv(output_path, index=False)

print("Exported:", output_path)
print("Rows exported:", len(ranked_queue))

display(ranked_queue.head(20))

Exported: ..\outputs\action_playbook_queue.csv
Rows exported: 30000

              content_id  score    reason_code     action_label
0   content_bbca724138f2  100.0  STALE_REFRESH  Refresh Content
1   content_40e140ba2934   80.0  STALE_REFRESH  Refresh Content
2   content_02b0d6e30129   80.0  STALE_REFRESH  Refresh Content
3   content_24abafed9707   80.0  STALE_REFRESH  Refresh Content
4   content_3a93f78aa0a5   70.0  STALE_REFRESH  Refresh Content
5   content_1dcf67c62f50   70.0  STALE_REFRESH  Refresh Content
6   content_928af3e22c80   70.0  STALE_REFRESH  Refresh Content
7   content_ab27c30d81f4   70.0  STALE_REFRESH  Refresh Content
8   content_b81e0f46cea9   70.0  STALE_REFRESH  Refresh Content
9   content_da54cb4484f1   70.0  STALE_REFRESH  Refresh Content
10  content_f2b4acf220d9   70.0  STALE_REFRESH  Refresh Content
11  content_56d7248c0b43   70.0  STALE_REFRESH  Refresh Content
12  content_a34d943a132c   70.0  STALE_REFRESH  Refresh Content
13  content_22ba8c872ab2   70.0  STALE_REFRESH  Refresh Content
14  content_fe16a55cd13d   70.0  STALE_REFRESH  Refresh Content
15  content_0af51f20a3da   70.0  STALE_REFRESH  Refresh Content
16  content_11da248ff221   70.0  STALE_REFRESH  Refresh Content
17  content_0a91db491d14   70.0  STALE_REFRESH  Refresh Content
18  content_2e2a634851a0   70.0  STALE_REFRESH  Refresh Content
19  content_cf56e2e2e282   70.0  STALE_REFRESH  Refresh Content

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.